---
title: "R Notebook"
output: html_notebook
---

Calaulate Risk and ambiguity aversion using loglikelihood

```{r}
library(stats4)
library(bbmle)
library(ggplot2)
```


```{r}
LL <- function(intercept, alpha, beta, gamma){
  safe = 5 ** alpha
  bet = (prob - beta *(ambiguity/2)) * amount ** alpha
  R = selection - 1/(1+exp(gamma * (safe-bet)))
  R = suppressWarnings(dnorm(R, log = TRUE))
  -sum(R)
}

calc_LL <- function(dbLL){
  selection <<-  dbLL$choice
  amount <<- dbLL$value
  prob <<-  dbLL$risk
  ambiguity <<- dbLL$ambiguity
  
  fit <- mle2(LL, start = list(alpha = 1, beta = 0, gamma = 1), method="L-BFGS-B", lower = c(alpha = 0, beta = -2, -Inf), upper = c(alpha = 2, beta = 2, Inf))
  
  return(coef(fit))
}
```

```{r}
db <- read.csv('/home/nachshon/Documents/Aging/Aging/RiskandAmbiguity/mon.csv')
db_all = data.frame()
subs <- unique(db$sub)

for (s in subs){
  df <- subset(db, sub == s)
  LL <- calc_LL(df)
  valid <- df$catch[1]
  validBin <- valid < 6
  temp = data.frame()
  #temp = data.frame(s, valid, validBin,
  #                  alpha <- LL[1], beta <- LL[2], gamma <- LL[3])
  db_all = rbind(db_all,temp)
}
```

